### ISSUE TITLE
Signup: ToS info should be displayed consistently

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#101311]
### Problem
Currently the ToS information is displayed in different position and has different styles on `Log In` vs. `Create an account`. After some [investigation](https://github.com/Automattic/wp-calypso/pull/101155#issuecomment-2717740447) pointing this information is essential for both instances and need to be placed before the actions, we should aim for consistency.

**Current implementation:**
![Image](https://github.com/user-attachments/assets/63be8f06-fd77-4499-93e0-d8f77adf8e13)

### Solution

* Keep ToS above the options, both on `Create an account` and `Log in` pages.
* Use the same subtitle style (font color, text size) in both of them.
* Each instance have it's different legal copy - keep it as it is.

### Proposed design

![Image](https://github.com/user-attachments/assets/2a11c201-b729-4cba-8d73-ef8b03befa61)

![Image](https://github.com/user-attachments/assets/6b0acab0-c770-4b0d-aa47-c2322f195869)

**Comment by alshakero** [comment]
This is fixed on wp.com now. But I have to mention that WPCC (Woo signup) has the same issue. cc @beaulebens.

**Comment by beaulebens** [comment]
@alshakero do you have a screenshot or some steps so I can see what you're referring to, and get the right people involved?

**Comment by alshakero** [comment]
Yes, if you go to [https://woocommerce.com/my-account/](https://woocommerce.com/my-account/) while incognito, you'll see the ToS and legal disclaimers are below the inputs. And the same issue occurs if you click Signup. Apparently, having the ToS below the inputs [is not great](https://github.com/Automattic/wp-calypso/pull/101155#issuecomment-2717740447).

**Comment by beaulebens** [comment]
@ebinnion this flow starts on WCCOM, but the pages are technically hosted on WPCOM (part of WPCC flows). I think someone on Desire (or even you) might be able to handle this the fastest. Basically we're just wanting to move the TOS line above the bulk of options/interactions;

<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/2c114f0e-b8a1-4ddd-8fff-4a9242bb0e98" />
<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/a82383a7-e0d1-4c8b-b430-0385a86f3bcc" />

**Comment by ebinnion** [comment]
I'm going to reopen this issue because I don't think we completely solved it the first time around.

https://wordpress.com/log-in isn't solved for example, which is one of the main entrypoints from the homepage.

![Image](https://github.com/user-attachments/assets/e8c7620e-eb2f-4fc8-a560-63988260853a)

But, also as I look at the code, it's pretty tangled and I'm sure that there are other flows that are going to need to be checked. We might as well get them in one go.

**Comment by mcliwanow** [comment]
This was closed automatically by an internal integration. I'll reopen it here and will close the issue when it's actually done
