### ISSUE TITLE
Editor: on sites with thousands of tags, tag suggestions are not providing a full representative list of tags

### ISSUE THREAD

**Issue by ashthemighty** [Automattic/wp-calypso#1367]
This is particularly an issue on sites with a large number of tags (originally reported by a user with 26,000 tags). 

When working in the Editor, if you start to type in a tag which should return several suggestion hits, only a small subset of tags are displayed. Sometimes as few as 2.

In this example, the term "Radu" was searched. According to the tags section of the WP Admin there are 161 items with that string in the tag and nearly 100 with "Radu" as the first word in a two word string (Radu is a common name in Hungary). When it is searched in the Editor, only 2 suggestions appear.

Note that searches on sites with fewer tags, as many as 200+, do not have this result.

**Comment by SiobhyB** [comment]
2437901-t

A similar issue was previously brought up in Automattic/calypso-pre-oss/issues/8905 and resolved by @nylen.

It seems like only the top 600 most frequently used tags are searched for, which can make it hard for owners of sites with a larger number of tags to search for the correct one for them.

As Ash noted, the user reporting this issue has over 26,000 tags on their site.

**Comment by designsimply** [comment]
#bug-scrub

I tested tagging a new post using the Calypso editor on a blog with 1633 tags and found that as long as the tag was used on at least one other post then it was returned in the tags suggestion list. If the tag exists on the blog but is not in use for at least one post, then the tag is not returned in the search list. I feel this is working as expected.

Closing because I was unable to reproduce the problem. If this issue comes up again, please include a specific example including the blog address, total number of tags, and an example tag you tried to search for that is in use on at least one other published post.

**Comment by taxifisch** [comment]
Hi!
I have a ticket from a user reporting this issue (ticket id 2437901). He claims

> The article:
> https://eurocom.wordpress.com/wp-admin/post.php?post=85009&action=edit
> - write in the taglist (címke): "román-" and i get 64 hits 
> - the new one , same article:
> https://wordpress.com/post/eurocom.wordpress.com/85009
> - open the taglist (PressThis-new1)
> - if i introduce "román-" i get only 13 hits (PressThis-new2.jpg)
> 

There are 29814 tags on the blog, and his example "román-" appears in 366 of them.
Maybe you could have a closer look on this? Thanks so much!

**Comment by SiobhyB** [comment]
Thank you for reporting @taxifisch. I was able to replicate on the above site and, so, am reopening this issue.

cc: @designsimply, in case you're able to see anything particular that's causing the issue with the above site.

**Comment by nylen** [comment]
Confirming this is still an issue.  We only load the most frequently used 1000 tags from a site ([reference](https://github.com/Automattic/wp-calypso/blob/2fedcc5/client/post-editor/term-token-field/index.jsx#L24)).

Marking this as low-priority as this should be sufficient for the vast majority of sites.

**Comment by lancewillett** [comment]
I think we can call this an edge case, noted by James in the previous comment — and a known limitation for performance reasons. Let's re-open in the future if we get a large amount of user reports.
