### ISSUE TITLE
Reader: Random spacing of action buttons in fullpost

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#23062]
![screenshot 2018-03-06 13 52 42](https://user-images.githubusercontent.com/4924246/37060638-bdf93ec8-2145-11e8-8e5f-46d529ccb8f9.png)

This happens because the buttons originate from the sidebar then are absolutely positioned at the top.

Proposed solutions:
1. Refactor `author-compact-profile` component and use CSS `order` property: https://github.com/Automattic/wp-calypso/issues/11355#issuecomment-283808581
2. Duplicate them in the markup then hide/show them as needed. We have an existing component like that called `current-section`. cc @shaunandrews 

cc @bluefuton

**Comment by davemart-in** [comment]
This should be fixed now.

**Comment by shaunandrews** [comment]
I don't see a related PR so I'm not sure what code was changed — but, I think this is more broken now than it was before. For example, on mobile safari I simply no longer see the action buttons. I still see the "external" icon, which also appears to be broken as its just kind of floating on its own:

![IMG_8082DD9174C0-1](https://user-images.githubusercontent.com/191598/195637611-2cd4afff-5e0e-4391-a3b0-93227c85c7c2.jpeg)

**Comment by davemart-in** [comment]
Yeah, I intentionally removed the floating action bar, since it was a duplicate of the action bar at the bottom of the post and it was just blocking your view of the content. We can definitely tweak the styles for the external icon though.
