### ISSUE TITLE
Editor: Image Editing for Private Sites

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#25115]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media
2. Click on an image and then click on the Edit button in the top toolbar

#### What I expected

That an image with "Edit Image" button at the top right comes up.

#### What happened instead

The image opened up, but there was not a button to edit the image.

#### Screenshots

**Edit Image button** for **public** site:
<img width="1434" alt="image-edit-button-public-site" src="https://user-images.githubusercontent.com/12064241/40608827-79bd10ba-6275-11e8-94a8-caf28eeef06d.PNG">

**No button** for **private** site:
<img width="1430" alt="image-edit-button-private-site" src="https://user-images.githubusercontent.com/12064241/40608835-7da22efe-6275-11e8-8317-0dc35d6cc86c.PNG">

As I understand, this is a CORS issue for private sites. Would it be possible to keep the **edit button** for private sites and link them to WP Admin for such edits?

#manual-testing and #user-report in #1173956-zen

**Comment by GeoJunkie** [comment]
Also had a #user-report in #4116019-hc

**Comment by wprhunt** [comment]
Have another customer trying to edit images but wanted to keep the site private as well:
#6719512-hc

**Comment by JoshuaGoode** [comment]
Encountered on 2557234-hc -- provided WP-Admin workaround.

**Comment by aportbury** [comment]
Another confused user in 11568931-hc. Provided a workaround using the WP-Admin editor instead.

**Comment by torres126** [comment]
Also in #31965

**Comment by arunsathiya** [comment]
Another one from @edequalsawesome - Initially reported in #9974062-hc / Follow-up #1928156-zen. From https://github.com/Automattic/wp-calypso/issues/31965

**Comment by lancewillett** [comment]
This one is a much bigger change than a simple bug fix. Please keep logging the customer feedback and suggestions. It's not as simple as a UI change, and probably requires system-level changes for security reasons, to avoid cross-site scripting limitations.

**Comment by kriskorn** [comment]
@lancewillett What if we made this as a simple UI fix _for now_ by keeping the **Edit** button and linking it to WP Admin for Private sites.

**Comment by lancewillett** [comment]
That's a good idea, Kris. It might be slightly jarring, though, as the page will reload in a different context.

**Comment by jsnajdr** [comment]
> This one is a much bigger change than a simple bug fix.

It's not a simple bugfix, but neither it is a major project. The root cause of the issue is that we don't have any REST API endpoint to retrieve the image data from media library. So we work around that by retrieving the image directly from the site. That's no longer a request to `public-api.wordpress.com`, where all authentication and cross-origin issues are solved, but a request to another origin. For private sites, where auth is required to get the image, this becomes a problem. Photon is not available there, CORS headers are missing...

See also a detailed discussion here: pMz3w-9qA-p2

I think that adding the endpoint to the WP.com API and using it in Calypso's image editor is a doable hack week project.

**Comment by khristiansnyder** [comment]
Another report at #2007626-zen.

Showed the WP-Admin workaround for now.

**Comment by lakellie** [comment]
Hi @jblz ! Hope you don't mind me pinging you here - I know you were working on the relaunch of private by default, so I wanted to bring this open issue to your attention, in case it wasn't brought up before. It came up when @kriskarkoski was helping a user in chat today. It's still not possible to edit images in Calypso when a site is set to private. If all new sites are now private by default, this should probably take a higher priority.

**Comment by kriskarkoski** [comment]
15465824-hc

The chat got messy when I couldn't see the Edit Image option without explanation. They were already a bit overwhelmed by Gutenberg so I ended up editing the image for them in WP Admin to avoid explaining another interface with them that won't be necessary (for this at least) once the site is launched.

**Comment by annbingle** [comment]
Hi and Good day!

Another user reported this here in 14675485-hc

Directed them to WP Admin as a workaround.

Thanks and have a great day!
Ann

**Comment by jblz** [comment]
Thanks for the ping, @lakellie -- I hadn't seen this issue. I agree that this is a pretty big hang up.

**Comment by lakellie** [comment]
Another report in 2565109-zen

**Comment by GeoJunkie** [comment]
User encountered this in 2661850-zen

**Comment by poojashetty18** [comment]
Another report in 20988021-hc

**Comment by ash1eygrace** [comment]
Another report in zd-#3087812

**Comment by aamills** [comment]
Another report in 25408342-hc - provided WP admin work around.

**Comment by simison** [comment]
We changed new sites to be "public by default" instead of private, so the frequency folks hit this might've lowered. Still an issue of course.

**Comment by jsnajdr** [comment]
A big part of this problem was solved a year ago by @jblz and @adamziel when implementing a media proxy endpoint for Atomic private sites in #39616 and followups. That allows to retrieve media files through a `public-api.wordpress.com` endpoint, solving the authentication and CORS problems present when Calypso tries to retrieve them directly.

This proxy should be extended to Simple sites, too, as the CORS issues are not specific to Atomic.

**Comment by supernovia** [comment]
Saw this on my own test site while troubleshooting another issue. Thanks @kriskarkoski  for pointing this out.

**Comment by zachspears** [comment]
Able to successfully reproduce this as well.

**Comment by rosepajaroja** [comment]
I can still reproduce this.

**Comment by ianstewart** [comment]
I can still reproduce this when a site is set to private. Works when sites are in coming soon mode however.

**Comment by BogdanUngureanu** [comment]
Since we've untangled the media screen, I don't believe we should fix this issue since the majority of the users will now get WP-Admin where the feature works.

Feel free to re-open it if it's still needed. :)
