### ISSUE TITLE
Gutenberg: Gallery images don't use Carousel

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#28614]
#### Steps to reproduce
1. Insert a gallery
2. View the post
3. Notice images link to individual images, rather than Carousel

#### What I expected
To be able to see a carousel like we had before

#### What happened instead
It links to individual images. So I click on an image, have to click back & click on another, etc.

#### Browser / OS version
Doesn't matter

#### Context / Source
https://en.forums.wordpress.com/topic/galleries-in-new-editor-frustrations/#post-3213062

**Comment by katinthehatsite** [comment]
Another report came as feedback in #1566861-zen

**Comment by jruud** [comment]
Another user with the same issue in #1574555-zen

**Comment by liviopv** [comment]
Another: #8223771-hc

**Comment by cecoates** [comment]
Related to same forum post's other issue, had a user who was confused at how the Gallery block can't create other gallery types mentioned here:

https://en.support.wordpress.com/gallery/ 

8231620-hc

Had to switch them to Classic.

**Comment by dcoleonline** [comment]
8378194-hc and we need to follow up in 1601145-zen

**Comment by lakellie** [comment]
Another user inquired about this in 8387949-hc

**Comment by eduardozulian** [comment]
8417109-hc

**Comment by kristarella** [comment]
I think it's being fixed here: https://github.com/Automattic/jetpack/pull/10646

**Comment by arunsathiya** [comment]
Noting that I am not able to see this behaviour anymore on WordPress.com simple sites or Atomic sites. The images in the WordPress Editor Gallery block appear in carousel. 

<img width="1281" alt="screenshot 2018-12-12 at 13 05 35" src="https://user-images.githubusercontent.com/18581859/49854004-e92f7980-fe0e-11e8-9e44-001d5ff6a30a.png">

<img width="1281" alt="screenshot 2018-12-12 at 13 07 35" src="https://user-images.githubusercontent.com/18581859/49854008-eb91d380-fe0e-11e8-9a97-915f9f8a01d8.png">

**Comment by carinapilar** [comment]
It seems that this is not going to fix old posts with galleries. When I [tested this](https://github.com/Automattic/wp-calypso/issues/28614#issuecomment-443175299) with the user, the [post I created](https://mytestsite.live/2018/11/30/gutenberg-gallery/#jp-carousel-768) still doesn't show the carousel arrows. While a [new post](https://mytestsite.live/2018/12/12/new-gutenberg-gallery-post/) I just created is showing correctly.
