### ISSUE TITLE
Change error message for "Scheduling share failed. Please don't be mad."

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#28766]
We show this error message when something goes wrong with scheduled posts:

> Scheduling share failed. Please don't be mad.

Code reference: https://github.com/Automattic/wp-calypso/blame/f5cdb7961ea5b116c9120838c2335b4f2622d7f3/client/blocks/post-share/index.jsx#L424

This wording is a bit cringeworthy and, more importantly, not particularly helpful. Here are my recommendations for updating this:

- Scheduling share failed. Please contact support. (with a link ideally!)
- Scheduling share failed. Please try again. (not sure if this will actually fix the problem?)

I'd prefer the top one as I doubt anything the customer does will be able to fix this without us intervening.

**Comment by jeherve** [comment]
This was introduced in #14550.

@artpi Do you think you could take a look?

**Comment by artpi** [comment]
This copy was a placeholder that we never got back round to :)
I have 0 knowledge of scheduling RN.
Yes, both of these wordings seem fine, but I don't know how it's actually possible to trigger this problem, what is the bigger scope of this feature working, etc.

**Comment by arunsathiya** [comment]
It seems to have been reported at https://github.com/Automattic/wp-calypso/issues/22043 as well, and seems to have been fixed here https://github.com/Automattic/wp-calypso/issues/22043#issuecomment-362570975

I tried following the steps on the other issue, but I am not able to reproduce this error. Naturally, I am not seeing this wording either. 

@annezazu Are you able to reproduce this at this time?

**Comment by annezazu** [comment]
I am not sure how to replicate this as I reported it while helping a customer who couldn't connect properly. The steps to follow don't help me replicate the broken state so I'm not sure what to do here. 

The fact it still lives in the code tells me it still exists and needs to be addressed though :). 

> Could you share how this error appeared and if it does appear in consistent manner?

This appeared when trying to schedule a post for a customer who had a Jetpack connection problem. I noticed it while helping them and reported it here to clean up the wording.

**Comment by annezazu** [comment]
Reopening because I believe this still exists in our code base here: https://github.com/Automattic/wp-calypso/blame/f5cdb7961ea5b116c9120838c2335b4f2622d7f3/client/blocks/post-share/index.jsx#L424 If I'm wrong, feel free to close :)

**Comment by tmmbecker** [comment]
Still exists! User just reported in 2772142-zen

<img width="459" alt="Image+2020-03-07+at+9 45 10+AM" src="https://user-images.githubusercontent.com/22805865/76145847-a97c2f80-605b-11ea-85e6-996df9b54eb6.png">

@jeherve any idea who would be a good person to ping about this? It's not really optimal messaging.

**Comment by jeherve** [comment]
I took a stab at it in #39964.
