### ISSUE TITLE
Paragraph Block: Drop cap option in paragraph block reappears without warning

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37295]
Please watch the "Editing a Page Template: Paragraph Block" testing video on this post: p58i-8d4-p2

There is a bug with the paragraph block when selecting drop cap and then setting another formatting option the drop cap disappears. When he clicks away from the paragraph block, the drop cap reappears. “Oh boy, what happened now? It keeps on switching from one style to the other”.

**Comment by jasmussen** [comment]
Good issue. I would like to share some context of why it behaves as it does. It behaves this way because technically you are editing a single rich-text field, and the drop-cap effect is added at a block level. For the first letter, the drop cap, to be editable, it has to be part of the same field, and the RichText component behaves in a broken way when the dropcap is present. Therefore the dropcap is removed whenever the text is focused.

It is possible that the issues with RichText have been addressed, enabling this now. @ellatrix are you aware of anything we can do here?

Alternately, the way to address this issue is likely going to have to be in the _flow_, that is by changing the UI design and tools to make it more clear what happens. I don't have any immediate good ideas for how to address this — perhaps adding animation so the dropcap scales down when the text is focused? But I would encourage creative thinking in absence of the technical solution.

**Comment by ellatrix** [comment]
I think the `contenteditable` issues with `:first-letter` still exist. Not sure what we can do. :|

**Comment by apeatling** [comment]
Could we make dropcap a different block or style instead? I guess it needs to read the first character, so a style gets tricky.

**Comment by jasmussen** [comment]
The drop-cap is definitely an advanced feature, which is why it is in the sidebar, and once of the principles we've built upon is the idea that you shouldn't have to use the sidebar to get your work done. In that vein, one thing to test could be to simply default the sidebar to off for new users, instead of on. It would arguably create a simpler experience right off the bat, and for developers it might also encourage them to lean in to a block-first development approach that long term will likely yield better results.

**Comment by apeatling** [comment]
Yes the user test exposed issues with showing the sidebar by default, more in this issue:

https://github.com/Automattic/wp-calypso/issues/37279

**Comment by jasmussen** [comment]
That seems like an excellent meta solution to this. We might even consider making the sidebar a dialog you open and close when you need it. Critical UI like publish dates and tags are duplicated in the pre publish UI anyway, exactly for this reason.

**Comment by ellatrix** [comment]
Idea: don't style the drop cap with `:first-letter` in the editor, but use a `span` for it. That's for sure going to be annoying to implement and annoying for themes, but it's the only way to properly solve this issue other than pushing browsers to fix the issues.

**Comment by jasmussen** [comment]
Once we have a span in the rich text area it feels like we are adding complexity that can result in tag-soup. It will also require changes to every theme that styles the dropcap, and finally we aren't sure that it will actually be a better user experience. 

For what it's worth, I personally feel like once you know how the dropcap feature works, what we have now is actually the best experience, all things considered. That's why I feel the way to solve this issue is to de-emphasize it as the advanced decorative feature that it is.
