### ISSUE TITLE
Page templates: Layout Grid columns do not adjust to additional columns

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#40462]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/block-editor/page/ (creating a new page on a simple site)
2. Select a page template that has a layout grid (e.g. Portfolio template with 2 columns of images, or Services template)
3. Select the Layout Grid block
4. Increase the number of columns in the grid (eg 2 -> 3, or 3 -> 4)

#### What I expected
Columns should space regularly as if it was a new grid block

#### What happened instead
The original columns stay positioned as if there is no extra column, and the extra column sits on top of them at the right.

#### Browser / OS version
Chrome 80.0.3987.149 / Mac OSX Catalina
(but it shouldn't be browser-specific)

#### Screenshot / Video
**Portfolio template:**

<img width="1423" alt="Screen Shot 2020-03-26 at 2 35 36 pm" src="https://user-images.githubusercontent.com/2031017/77607673-3b969a00-6f6f-11ea-904f-605b77c7edb6.png">

**Services template:**

<img width="1365" alt="Screen Shot 2020-03-26 at 2 35 19 pm" src="https://user-images.githubusercontent.com/2031017/77607687-481af280-6f6f-11ea-97f2-0b239ba000a3.png">

#### Context / Source

The issue appears to be that the CSS classes from the original grid are not being removed when the new classes are added.
E.g. in the grid for portfolio template these persist:
`column1-desktop-grid__span-6 column2-desktop-grid__span-6 column2-desktop-grid__start-7`
and in grid for services:
`column1-desktop-grid__span-2 column1-desktop-grid__start-2 column2-desktop-grid__span-4 column3-desktop-grid__span-4 column3-desktop-grid__start-8 column3-tablet-grid__start-5`

I fixed the problem for the customer by manually removing these classes from the block's markup.

I suspect that this problem will happen in all page templates, but I only tested the two I've mentioned.

#user-report 19705368-hc

**Comment by obenland** [comment]
@mkaz Is that a known issue? Should this be in [Automattic/block-experiments](https://github.com/Automattic/block-experiments)?

**Comment by mkaz** [comment]
Ping @jasmussen and @johngodley 
We don't have to move the issue, but likely to get resolved in that repo.

**Comment by johngodley** [comment]
The block should adjust the classes as appropriate. I'll look into this in the block experiments repo, and update back here when there's a solution.

**Comment by johngodley** [comment]
@kristarella sorry it's taken so long to look at this. I couldn't reproduce the problem, and the grid behaves as expected when changing the number of columns. Is it still happening? If so could you record a screencast and include the URL of a page with an incorrectly adjusted grid?

**Comment by jasmussen** [comment]
Using the suggested portfolio template as noted, immediately I did not see an issue, just like John:

![grid](https://user-images.githubusercontent.com/1204802/80353664-f0c1b800-8875-11ea-85af-10c1a7a4dff5.gif)

However I was manage to create a situation that wasn't super ideal:

![issue](https://user-images.githubusercontent.com/1204802/80353767-1a7adf00-8876-11ea-9571-9067ae131037.gif)

To explain what's going on there, as soon as the image gets resized, it _keeps that size_ even when the number of columns is changed. 

The bug here is that the image block does not reset correctly to its new context, and this is actually an issue even in the core columns block:

![cols](https://user-images.githubusercontent.com/1204802/80355391-53b44e80-8878-11ea-9a0a-14f82a3f78f0.gif)

For that reason, I created a ticket for that in the core project, and will close this one: 

https://github.com/WordPress/gutenberg/issues/21912

Thanks! And let me know if the issue was a different one after all, and I'll reopen!

**Comment by kristarella** [comment]
Sorry, this is still an issue. It seems I missed a step that I thought was obvious from the screenshots, but I should have stated it. The columns appear fine in the editor, it is on the front of the site that the problem occurs.

The updated steps to replicate are:

1. Starting at URL: https://wordpress.com/block-editor/page/ (creating a new page on a simple site)
2. Select a page template that has a layout grid (e.g. Portfolio template with 2 columns of images, or Services template)
3. Select the Layout Grid block
4. Increase the number of columns in the grid (eg 2 -> 3, or 3 -> 4)
5. Add content to additional column
6. Preview page

**Comment by jasmussen** [comment]
Thanks for the added steps. Can confirm, thanks for reopening. I'm taking a look now:

![steps](https://user-images.githubusercontent.com/1204802/80464398-03052a00-893a-11ea-931a-d957121d92ee.gif)

**Comment by jasmussen** [comment]
I've found some more info.

The grid has 12 grid columns. By default the portfolio example we've used here has two columns, each spanning 6 grid columns.

It appears that when you change from 2 to 3 content columns, even though the editor correctly reflects this, it isn't actually saved properly, so when you preview or publish, you see 2 content columns each spanning 6 grid columns, and the last content column spanning 4 grid columns, i.e. overlapping.

If I adjust the column spans in the editor then save and preview again, the issue is fixed: 

![steps](https://user-images.githubusercontent.com/1204802/80465636-a7d43700-893b-11ea-9a6f-d2d2ff18b1f6.gif)

This suggests that there might be an issue with either:

- How the portfolio template was created
- How the portfolio is saved when updated 

@johngodley do you have any insights here?

**Comment by johngodley** [comment]
I've reproduced the problem, and it's related to Gutenberg re-adding old CSS classes, but only when the grid has non-default column offsets.

A fix is ready in https://github.com/Automattic/block-experiments/pull/83 and, if confirmed, will make it's way onto .com soon.

**Comment by johngodley** [comment]
This is now fixed and deployed.
