### ISSUE TITLE
Editor: When a color palette is chosen for the site, poor-contrast color changes happen in the UI

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#47117]
When a custom color palette is loaded on a site, the `:hover` and `:focus` state of UI elements in Gutenberg claim the primary color of the site as the background color, while the text color remains black. This creates a poor contrast and horrible experience while using the editor:

<img width="475" alt="Screen Shot 2020-11-02 at 21 56 14" src="https://user-images.githubusercontent.com/31009008/98153417-28eb2880-1ea1-11eb-8e9a-5c63dcb74d20.png">

<img width="1248" alt="Screen Shot 2020-11-02 at 21 55 30" src="https://user-images.githubusercontent.com/31009008/98153484-45876080-1ea1-11eb-9924-f68cd4ed5905.png">

<img width="526" alt="Screen Shot 2020-11-02 at 21 57 29" src="https://user-images.githubusercontent.com/31009008/98153490-46b88d80-1ea1-11eb-8ef1-36186182ad71.png">

It seems to be isolated to Varia-child themes:

Not reproducible: Spearhead, Twenty Twenty, Radcliffe 2, Seedlet
Reproducible: All Varia-child

#### Steps to reproduce

1. Starting at URL: https://wordpress.com
2. Activate a Varia-child theme in Design > Themes
3. Design > Customize > Colors & Backgrounds, pick a custom color palette, "Save changes"
4. Open a post in the editor

#### What I expected

I expected the UI elements to retain the normal Gutenberg UI color palette as seen below with the theme Seedlet, for example:

<img width="964" alt="Screen Shot 2020-11-04 at 13 39 48" src="https://user-images.githubusercontent.com/31009008/98154803-52a54f00-1ea3-11eb-8eda-554bedd26077.png">

#### Context / Source

#dogfooding

**Comment by davipontesblog** [comment]
On this same site I tested and got these screenshots, using the same theme Maywood and the same color palette, it doesn’t show those issues anymore. The same site and all. I did go to the Colors and Backgrounds in the Customizer, backed to Default, and then changed it to the same palette again, I wonder if that forced the caching to clear.

I am going to close this issue until we can reproduce again.

Thanks @rickybanister for your help testing!

**Comment by davipontesblog** [comment]
I am reopening this issue as it continues to happen. More details here: p9Jlb4-1Zd-p2#comment-3165

**Comment by davipontesblog** [comment]
@simison this issue could be affecting many, many users, since new site owners typically will land one version or another of Varia child themes during signup. It affects the experience of using the editor for the first time negatively. I recommend we try to prioritize if possible.

**Comment by simison** [comment]
Thanks for the nudge! I'm just about to sign off to be AFK tomorrow but let's ping @scruffian @kjellr @rickybanister for priorization-help and if you can also drop this at #create-gardeners that would be ace!

**Comment by andrewserong** [comment]
I've added a high priority to this one, but I believe it'll need to be prioritised by the themes team. CC: @Automattic/theam

**Comment by andrewserong** [comment]
A possibly related issue: https://github.com/Automattic/themes/issues/2855

**Comment by jffng** [comment]
We recently pushed a [change to Maywood](https://github.com/Automattic/themes/pull/2879) that fixes a related issue (https://github.com/Automattic/themes/issues/2855).

I'm not certain this solves the issue you're reporting here, because the fix we merged was only specific to Maywood. But I can't recreate the issue you're reporting. I tested a few other Varia themes (Balsana and Leven) with that patch applied.

Re-opening in case you can still replicate, and can add more detail on how to do so. Thank you!

**Comment by scruffian** [comment]
I think this happens when the frontend color pallettes load instead of the editor ones. I've had a look at the code and I can't work out why/when this happens. I hope that soon we'll be able to start using global styles instead of color pallettes.

**Comment by cathymcbride** [comment]
@davipontesblog can you still repro?

**Comment by davipontesblog** [comment]
> @davipontesblog can you still repro?

@cathymcbride I can't, I tried creating a new site and picking a Varia theme, and then changing color palettes in the Customizer to see if it would happen, but it didn't. I know this one is a weird one though as in how it happens _sometimes only_. I will continue to keep an eye. @annezazu you experience this with your testing of WordPress.com the other day, do you still have the blog address so we can try to repro?

**Comment by annezazu** [comment]
Can confirm this is still a problem for me. This is happening on https://letslifechat.com/ and I'm happy to give anyone access if it helps! Here are screenshots for good measure:

Front end:

<img width="1436" alt="Screen Shot 2020-12-07 at 10 39 00 AM" src="https://user-images.githubusercontent.com/26996883/101384992-6c59fd80-3878-11eb-8268-21850bc69902.png">

Editor UI:

<img width="1437" alt="Screen Shot 2020-12-07 at 10 38 48 AM" src="https://user-images.githubusercontent.com/26996883/101385064-809dfa80-3878-11eb-8339-fede59c75265.png">

**Comment by david-szabo97** [comment]
Tried to reproduce this but couldn't find any way. Are there reliable reproduction steps?

**Comment by annezazu** [comment]
For me, I built my site and didn't change the defaults (aka if a button default was blue, I let it stay blue) before going into the customizer to change the color scheme. After changing the color scheme, my UI got busted for lack of a better term ;) causing colors I had picked for the site to take over the UI of the core editor. It might be worth noting that I used page layouts a good bit of the time (over blank pages) in case that makes a difference.

**Comment by cathymcbride** [comment]
I'm not reproing either, so I'm going to lower the priority of this. If we get more reports or a solid repro, we'll bump it back up.

**Comment by davipontesblog** [comment]
@cathymcbride , @david-szabo97 - I don't know if it helps but if you have access, you can see this live in https://letslifechatcom.wordpress.com/wp-admin/post.php?post=30&action=edit. I just tried and I can repro as well. I thought maybe being able to repro on this site and checking the browser inspector may help identify the issue?

**Comment by simison** [comment]
@jffng @scruffian could you have a look at the site above to see if it's the same issue? Thanks!

**Comment by scruffian** [comment]
What seems to happen is that the color palette is cached, so it takes some time to update everywhere, which means things look pretty broken until the changes propagate. I plan to look into changing how this works for Varia themes to match how things work in Seedlet to see if that solves the problem.

**Comment by simison** [comment]
@scruffian Assuming this can be closed already, as from what I know this has been fixed in themes and we haven't heard about new reports?

Feel free to re-open if still active issue.

**Comment by annezazu** [comment]
This is still active on the same site mentioned above. Same screenshots mentioned here still apply: https://github.com/Automattic/wp-calypso/issues/47117#issuecomment-740070466 If I create a new page, I find the styles still don't match in editing vs preview:

Editing:

<img width="1427" alt="Screen Shot 2021-02-22 at 8 24 47 AM" src="https://user-images.githubusercontent.com/26996883/108729435-c0739600-74e7-11eb-91ee-0a4955dcc751.png">

Preview:

<img width="1407" alt="Screen Shot 2021-02-22 at 8 24 53 AM" src="https://user-images.githubusercontent.com/26996883/108729206-85716280-74e7-11eb-8b32-4dcdb69adf71.png">

**Comment by scruffian** [comment]
👌  added back to our board...

**Comment by annezazu** [comment]
I logged in today to write a new post and the issue is now resolved on my individual site! Feel free to close unless there are other reports I'm unaware of.

**Comment by davipontesblog** [comment]
@annezazu thanks for reporting back on this. Let's close the issue for now and reopen if it ever comes up again.
