### ISSUE TITLE
Hero Flow loading screen tracks events

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58212]
Related to https://github.com/Automattic/wp-calypso/pull/57640
Low priority, does not block shipping the Blogger & Build flows.

When testing tracks events on the loading screen in the Build & Write flows, it looks to me like the `calypso_signup_processing_screen_show` is firing twice.

![image](https://user-images.githubusercontent.com/5665959/142302150-2ba4e2d6-9c9e-44a9-a02b-b9ebb620418f.png)

![image](https://user-images.githubusercontent.com/5665959/142302131-ade818f0-1ae2-4b26-b976-0d2c26212767.png)

### What happened

`calypso_signup_processing_screen_show` is firing twice when the loading screen appears after design selection

### What I expected to happen
`calypso_signup_processing_screen_show` would fire once

**Comment by arthur791004** [comment]
@autumnfjeld 

> When testing tracks events on the loading screen in the Build & Write flows, it looks to me like the calypso_signup_processing_screen_show is firing twice.

The screenshot doesn't mean the event is sent twice. `Record event "%s" called with props %o` logs the event with all of the props. On the other hand, `Recording event "%s" with actual props %o` logs the event with all of the props, and those value is not `undefined`.

Or maybe the “twice” you mean is the two screenshots (The one with “step=intent” and the other with “previous_step=starting_point”. If so, I think the issue is that we might go to the invalid step after finishing the last one, and then we would redirect to the first step as the previous step is invalid. Then, the event is sent again due to the change of step. But this problem is already fixed by https://github.com/Automattic/wp-calypso/pull/58092, so the event should be correct now 🙂

> This one is also missing starting_point=write

Do you mean that we also need to add `starting_point` to the props of `calypso_signup_actions_complete_step` event? Or you mean that we the starting point step doesn't send `calypso_signup_actions_complete_step` event? If the former, we should create a PR to add `starting_point` to the props of that event.  If the latter, it won't send because this event is only triggered by the step with API request but the starting point step doesn't have.

**Comment by autumnfjeld** [comment]
Sorry about the delayed reply. I have to go run through the events again, because some things still don't make sense. But this is low priority.

I've also updated the description to make it less confusing.
