### ISSUE TITLE
[E-mails] [Liked post] Generic Gravatar

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#62996]
### Quick summary

Since the email notifications for WP.com were overhauled last week, email notifications for Likes are missing the user's Gravatar. 

### Steps to reproduce

Receive an email notification for a Liked post.

### What you expected to happen

The email should display the Liker's Gravatar

### What actually happened

The email displays a generic Gravatar instead

![_Team_Canada__eh___Caroline_liked_your_post__Welcome__Mike__and_welcome_back_ Nick___-_kathryn_a8c_com_-_Automattic_Mail](https://user-images.githubusercontent.com/7662449/164981165-bda35fc2-0355-4858-98ea-f8592f8d3da5.jpg)

**Comment by yansern** [comment]
@Automattic/apex Wondering if there's a disparity with the Liker's ID when e-mails are sent out from `email-overrides.php`.

**Comment by formosattic** [comment]
I'm seeing the same generic Gravatar for `New subscriber!` notification.
![image1](https://user-images.githubusercontent.com/15944096/165268532-78c7d54d-577f-444b-9145-87659f2abd4d.png)

**Comment by mashikag** [comment]
Hey @formosattic ! 👋  Can you help me with identifying the subscriber username from your example? It does not seem to be "Oo Long". I just want to make sure the user has actually custom image gravatar. I was not able to repro the issue for "New subscriber" email, despite being able to repro the issue with post liked email notification. 

<img width="626" alt="Screenshot 2022-04-27 at 09 51 09" src="https://user-images.githubusercontent.com/2019970/165468902-b9e540db-7632-4345-be50-cf9d3ca4d9a8.png">

**Comment by mashikag** [comment]
The email notifications for Likes were addressed and fixed in D79542-code.

@formosattic please confirm whether you are able to reproduce the missing gravatar image on the "New Subscriber" notification email, or whether perhaps the subscriber user used in [your report](https://github.com/Automattic/wp-calypso/issues/62996#issuecomment-1109566222) did not have any gravatar image.

**Comment by vinnykaur** [comment]
Also reported at zd-5166582 and zd-5168074

**Comment by mashikag** [comment]
> Also reported at zd-5166582 and zd-5168074

The two issues are specific to "Liked" email notification. However they are different to this issue. 

The two are asking to include a link to a blog of the "liker" in the email notification. Just like it used to be in the previous email implementation.

**Comment by mashikag** [comment]
Since there is no further reports of any issues with the gravatar in the "New Subscriber" email I will close the issue for now. 

@formosattic please re-open the issue if needed. 🙂

**Comment by formosattic** [comment]
Thanks @mashikag!

My test user indeed didn't have a custom Gravatar, and `Hide my Gravatar profile` was turned on. But I've set a custom Gravatar now, and turned off `Hide my Gravatar profile`, and the generic Gravatar still shows. Maybe the new Gravatar is slow to get refreshed. I'll leave this closed. 

![image1](https://user-images.githubusercontent.com/15944096/166128472-b41c1f13-29ef-4fe6-abfa-a1e34fdd1f49.png)

**Comment by ivan-ottinger** [comment]
> Maybe the new Gravatar is slow to get refreshed.

That was also my experience when I was experimenting with Gravatar changes.

**Comment by vinnykaur** [comment]
I got another user where they are missing Gravatar image on the emails. I checked and `Hide my Gravatar profile` is turned off for the user.

Screenshot: https://d.pr/i/IwLMvJ 

Re-opening this so that someone can look into it.

Reported in zd-5182954

**Comment by ivan-ottinger** [comment]
> I got another user where they are missing Gravatar image on the emails. I checked and Hide my Gravatar profile is turned off for the user.

Thanks for the report @vinnykaur.

This one required a bit of digging, but it turns out the issue isn't related to the new email templates. I tested sending an email using the old template and the Gravatar image was still missing.

The culprit is the deactivated "Show Avatars" setting in `wp-admin/options-discussion.php`:

![Markup on 2022-05-03 at 14:56:58](https://user-images.githubusercontent.com/25105483/166456908-07e5d705-dc8a-47e2-b63a-e281b69a7f89.png)

Once the user activates the setting, their Gravatar will start displaying. :)

I am closing this issue, but feel free to reopen if anything. Cheers.
