### ISSUE TITLE
Gutenberg - Margin controls on any block that involves layout 

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#64438]
### What

Blocks like Cover block, Media and text block , do not have the provision to adjust margins ( especially top and bottom margins ) . That leads to awkward white gaps in layouts

![image](https://user-images.githubusercontent.com/4162931/172545647-7ed5fa7d-53e9-4767-a0d4-361c49de449b.png)

Blocks seem to have padding controls, but not margin. 

### Why

Without this control user has to depend on CSS which defeates the purpose of Gutenberg / FSE making things code free. 

context : [35742471-hc](35742471-hc)

### How

Try adding two cover blocks one below other and check the gap between the two.

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Updated main description of report - No

📌 FINDINGS/SCREENSHOTS/VIDEO
<img width="1510" alt="Markup 2022-06-23 at 09 09 58" src="https://user-images.githubusercontent.com/83325600/175319880-64e1c6ce-b44d-48ac-84e1-da528a7e70c0.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Feature request kept

**Comment by nagpai** [comment]
35898535-hc

Group blocks and paragraph blocks seem to have margin that cannot be controlled. Leading to awkward white spaces 

![image](https://user-images.githubusercontent.com/4162931/175764019-5540e953-575d-4640-b585-5c5061d5cb4f.png)

**Comment by nagpai** [comment]
#35897506-hc

**Comment by carinapilar** [comment]
This seems to be similar to this other issue: https://github.com/Automattic/wp-calypso/issues/62782

As mentioned in the above comment, this also happens with Paragraph blocks, there's a gap on the top when using a paragraph with an image on the left (or on the right), for example:

![ParagraphMargin](https://user-images.githubusercontent.com/16104522/176414600-3d4b0be0-bb7e-444a-b8f2-7986dc3bf82a.jpg)

This doesn't happen with older themes. The above was with Twenty Twenty-Two, but it works with Hemingway Rewritten.

And the issue is with that same `margin-block-start: var( --wp--style--block-gap );` mentioned on the GH link above.

**Comment by daria2303** [comment]
One of the interactions about it: 5335066-zd-woothemes, had more in the past

**Comment by jordesign** [comment]
It looks as though this is related to the `block_gap` functionality Gutenberg - but if I'm honest - I can't tell if/where it is being worked on and/or if this is a core issue - or something Themes need to opt in to.

@annezazu can you provide any insight to if the issue mentioned here is something being addressed in core? Potentially related issues I see are:

* https://github.com/WordPress/gutenberg/issues/36797
* https://github.com/WordPress/gutenberg/issues/34716
* https://github.com/WordPress/gutenberg/issues/27315
* https://github.com/WordPress/gutenberg/issues/28356

**Comment by annezazu** [comment]
👋🏼 Hey hey! 

> Blocks like Cover block, Media and text block , do not have the provision to adjust margins ( especially top and bottom margins ) . That leads to awkward white gaps in layouts

This specifically relates to [Consistent Dimension controls ](https://github.com/WordPress/gutenberg/issues/28356). Going a step further though, alongside the dimensions, the problem remains that there needs to be an easier way to reset block gap (as you can see [discussed in this issue about adding margin support to the group block](https://github.com/WordPress/gutenberg/pull/37344#issuecomment-1038862197)). 

Can you all gather a few more examples/share more here @jordesign? From there, I can see about opening an overall _adjacent_ issue to the consistent dimension controls one as adding controls is just one piece of this.

**Comment by SaxonF** [comment]
Some adjacent thinking and exploration surrounding a more complete set of layout tools [here](https://github.com/WordPress/gutenberg/issues/42385)

**Comment by jeherve** [comment]
36074196-hc

Workaround - CSS

**Comment by annezazu** [comment]
@jordesign wanted to loop back on the above examples to see if we had a list of a few (3-4 ideally). No rush! Just looping back.

**Comment by devNigel** [comment]
I can see the similar gap between Group blocks, Headers and Footers. It is not possible to get rid of this space using editor features.

The gap is introduced by this CSS:

```
.wp-site-blocks > * + * {
    margin-block-start: 1.5rem;
}
```

Screenshot:

![ovRWY2.png](https://user-images.githubusercontent.com/33957570/186394595-ef5503ad-9472-4786-961a-f2a19e96f80a.png)


User report: 36590943-hc

- [ ] Follow up: 5502805-zd-woothemes

**Comment by Robertght** [comment]
@annezazu we might've lost this between the different channels. I've shared a list of my findings regarding similar experiences, but I'd say they don't all share the same factors here: pc4f5j-2dU-p2#comment-2805

https://github.com/Automattic/themes/issues/6197
https://github.com/Automattic/themes/issues/5578
https://github.com/Automattic/themes/issues/3453 - > https://github.com/WordPress/gutenberg/issues/28647
https://github.com/Automattic/themes/issues/3159 
https://github.com/Automattic/themes/issues/5895

I'm not quite sure about this either, but looping in @pbking and @jeffikus for a second opinion on this.

**Comment by jordesign** [comment]
@annezazu - it's been tricky to find interactions around this - as the wording/description of the issue when dealing with users is pretty varied and generic (around gaps between blocks) but anecdotally I know I've run into it...

A specific case (from empathy testing) is in the home page of Pe8rBq-2-p2 where there is no way to close the gap between Cover blocks within the Query/Loop of the layout.

**Comment by annezazu** [comment]
Thank you all for trying to gather more of these! Let's keep this open and see if more items/specific use cases come up for a feedback style issue. For now, there's far more momentum around consistent dimension controls that should help resolve the original issue described here: https://github.com/WordPress/gutenberg/issues/43241 You can see what's planned for margin and blocks specifically here: https://github.com/WordPress/gutenberg/issues/43243

**Comment by cuemarie** [comment]
Thanks for weighing in on this @annezazu and @jordesign ! Based on the advice above, I'm marking this as triaged to keep open and on our radar for now. Thanks!

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by happychait** [comment]
User report 5759835-zen

**Comment by carinapilar** [comment]
This issue makes it impossible to create nice site sections with Cover blocks, which is a bummer. I was looking to create a _shadow effect_ using 2 Cover blocks, to have a nice transition between blocks like this (example from a third-party theme not using Gutenberg):

![shadow-effect](https://user-images.githubusercontent.com/16104522/205991942-46dedca8-6625-4f1a-a00e-67280945a375.jpg)

Since this result isn't possible to achieve with one Cover block and its Gradient option, using 2 Cover blocks also isn't possible because of this gap issue, since this would be the result:

![space-between-cover-blocks](https://user-images.githubusercontent.com/16104522/205992308-ea9226f3-59c0-421b-859d-7e0c3783d3bc.jpg)

I would expect that adding zero to the blocks' padding would remove that space, but that doesn't happen.

**Comment by miksansegundo** [comment]
+1 for adding margin controls on template part blocks too because that would allow us to reset the global block gap as suggested in the issue https://github.com/WordPress/gutenberg/issues/47637.

See how the template part block gets the global block gap and cannot be removed because of the lack of margin controls:

<img width="1292" alt="Screenshot 2566-06-02 at 12 10 03" src="https://github.com/Automattic/wp-calypso/assets/1881481/a4f0d9fb-302d-4270-82fb-c9d9effb1fe0">


For context, the padding controls were removed in [Remove color, spacing, and layout options for Template Part block](https://github.com/WordPress/gutenberg/issues/30732).
