### ISSUE TITLE
Marketplace: Improving search states

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#68492]
As part of the overall marketplace, design revamp exercise, we’d like to improve our existing search states.

**Results page**
Scenario; a user searching for a query and the page returning results

![results_new](https://user-images.githubusercontent.com/97929097/193325734-b010859c-0b65-4a76-a998-33da6d92d487.jpg)

- Remove the existing (yellow) highlights of the query on the page.
- Keep the categories in the main header allowing users to explore other plugins.
- We follow [the same headline & description pattern](https://href.li/?https://github.com/Automattic/wp-calypso/issues/67239) as we have on the landing page and categories.

**No results page**
Scenario; a user searching for a query and the page returning results

![noresults_current_new](https://user-images.githubusercontent.com/97929097/193325749-6acaa722-1ba3-4d78-b8a9-57f458183c11.jpg)

- Add the headline of the page
- Add the plugin categories to the main header allowing users to explore
- List our top paid plugins in case of no search results
- We follow [the same headline & description pattern](https://href.li/?https://github.com/Automattic/wp-calypso/issues/67239) as we have on the landing page and categories.

**This mockups already have the [new top header](https://github.com/Automattic/wp-calypso/issues/67285)

**Comment by lsl** [comment]
Look's good vini, for development lets break this up into some smaller issues to deploy, something like:

- ~Remove the existing (yellow) highlights of the query on the page.~ (Fixed on [69379](https://github.com/Automattic/wp-calypso/pull/69379))
- Keep the categories in the main header allowing users to explore other plugins.
- No results page: Add the headline of the page
- No results page: List our top paid plugins in case of no search results
- ~We follow [the same headline & description pattern](https://href.li/?https://github.com/Automattic/wp-calypso/issues/67239) as we have on the landing page and categories.~ ~(This last part is blocked by can be done as part of [67781](https://github.com/Automattic/wp-calypso/pull/67781#issuecomment-1250436102))~ - This should be fixed now.

**Comment by lupus2k** [comment]
Hey @vinimotaa, we still don't have the possibility to search within categories, what should we do when searching if we are on a category? Should we remove the selected category, or should we select "discovery" instead?

**Comment by lupus2k** [comment]
@vinimotaa I will follow the screenshot, nothing selected

**Comment by vinimotaa** [comment]
Hi @lupus2k, on the search results page (with or without results), we shouldn't select any category - it displays empty. I haven't yet thought of search by category - this could be another exercise.

**Comment by lupus2k** [comment]
Thanks @vinimotaa !
