### ISSUE TITLE
[New Comment] Missing post author notifications for new comments on P2 posts

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#69144]
Context: p1666035976333449-slack-C02TCEHP3HA

Regression possibly made by https://github.com/Automattic/wp-calypso/issues/66651

**Comment by TimBroddin** [comment]
Fixed in D90094-code

**Comment by zdenys** [comment]
@TimBroddin given the timeline of the above, I suspect that some WordPress.com users may have been affected by this. But I cannot be certain 100%. In 5660756-zd-woothemes we have a user who stopped receiving email notifications about new comments on their site since October 20th. They haven't changed any settings on the site. 

Could it be that the above fix didn't fix their case?

**Comment by TimBroddin** [comment]
Hi @zdenys,

Thanks for bringing this to our attention.

We did some investigation: p1666944663583219-slack-C02TCEHP3HA
and will deploy a patch later today (when it's reviewed): D91010-code

**Comment by TimBroddin** [comment]
Hey @zdenys 👋

This patch just landed, which should fix it for the user: D91010-code

Please keep me updates if for some reason they still don't receive new comment e-mails.

**Comment by zdenys** [comment]
Thank you very much for such a quick investigation and fix @TimBroddin  🥳 I've informed Happiness about this: p1667035380247309-slack-CB0B2G43X

**Comment by danielbachhuber** [comment]
There might be an issue on p2 breath sites too p1667516446086859/1666035976.333449-slack-C02TCEHP3HA

**Comment by danielbachhuber** [comment]
> There might be an issue on p2 breath sites too

Fixed with D91652-code
