### ISSUE TITLE
Mark tag with class and style attributes showing unexpected yellow background color

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#70675]
### Quick summary

Reporting this quickly as it's similar to https://github.com/Automattic/wp-calypso/issues/57036 , but the workaround there did not work. Forgive the lack of reproduction tests!

In this case, the user's text within `<mark style="background-color:rgba(0, 0, 0, 0);color:#ddca3e" class="has-inline-color">"SAMPLE TEXT"</mark>` was showing with an unexpected yellow background color on the live site. 

### Steps to reproduce

Have not had a chance to test repro-ing yet, but here's what I'm seeing: 

1. Simple site, Theme Toujours
2. In a post, add the following via the Code Editor: 

```
<!-- wp:paragraph {"style":{"typography":{"fontSize":"15px"}}} -->
<p style="font-size:15px"><strong>Maeno Tomoaki as <em><mark style="background-color:rgba(0, 0, 0, 0);color:#ddca3e" class="has-inline-color">"Riku Nishijima"</mark></em> - </strong>Lupin <em>(Code Realize)</em>, Yamanbagiri <em>(Touken Ranbu)</em>, Red <em>(TaiAli),</em> Camus <em>(Utapri)</em>, Radius <em>(Period Cube)</em>, Keisuke Sanjo <em>(CollarxMalice),</em> Kunitaka Tojo <em>(Winters Wish)</em></p>
<!-- /wp:paragraph -->
```

### What you expected to happen

![Markup on 2022-12-01 at 16:38:36](https://user-images.githubusercontent.com/27249804/205181817-6100e66d-0c6d-4a12-85d3-c1379cdfe9cb.png)

For the text to appear in the color selected, as shown in the editor

### What actually happened

<img width="1443" alt="Markup 2022-12-01 at 16 28 18" src="https://user-images.githubusercontent.com/27249804/205181833-ce2f0671-c67d-41f9-9d43-83d75a303f84.png">

The inline color text also displays a yellow background. Since the `mark` tag is not bare, the CSS solution from  https://github.com/Automattic/wp-calypso/issues/57036 does not solve it, and this seems like a similar, but slightly different, issue.

### Context

38381642-hc

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

None

### Severity

None

### Available workarounds?

None

### Workaround details

Provided the following CSS code as a workaround: 

```
mark {
  background-color: rgba(0, 0, 0, 0);
}
```

**Comment by cuemarie** [comment]
Also, I asked the user if they'd cut & pasted any of their content, and they said they did not. They composed all of their content in the post in question right in the editor. 

To me, that rules out this being the issue as well: https://github.com/Automattic/wp-calypso/issues/61721 (which also suffers from bare `<mark>` tags

**Comment by artpi** [comment]
Similar ticket with this issue:
5760374-zd-woothemes

**Comment by sophiegyo** [comment]
A forum post too: https://wordpress.com/forums/topic/unwanted-yellow-highlight-appearing-in-text-for-gutenburg-based-blocks/

User's two sites are both Simple, using the Plane theme.

**Comment by sophiegyo** [comment]
And another forum post - user edited their content to remove the highlighting:
https://wordpress.com/forums/topic/weird-highlighting-how-to-remove/?view=all

Simple site, using Hever theme.

**Comment by louinel** [comment]
Similar issue: 
5759861-zd-woothemes 
5760658-zd-woothemes
5762441-zd-woothemes, on a Premium plan, I've sent the CSS code shared below. 
5762570-zd-woothemes, I also shared the CSS code with them.
5772122-zd-woothemes, Premium plan, CSS workaround shared with them.

**Comment by carinapilar** [comment]
Got one on 38428709-hc, I was able to replicate it on a Simple site with Twenty-Twenty, wrote some text, and when using the Highlight option to change the text color, it added a yellow background too.

**Comment by donalirl** [comment]
I encountered this in #37875439-hc. Didn't realize it was a bug as they had an old theme. I gave this CSS fix:

```
/* remove background color from highlighted text */
p mark {
background-color: unset;
}
```

**Comment by hacchism** [comment]
Another report in #38435499-hc. Gave them a CSS fix. Simple site using Hever theme.

**Comment by MaxPhilip** [comment]
Another report in 5762009-zd. Provided CSS workaround.

**Comment by MaxPhilip** [comment]
Another report in 5760276-zd. Personal plan.

**Comment by christianguerrag** [comment]
Another report in 5762089-zen. Hive theme (Premium, Retired). Premium plan, shared CSS workaround.

**Comment by hacchism** [comment]
Another report in 5761205-zd. Personal plan.

**Comment by hacchism** [comment]
[Another one](https://wordpress.com/ja/forums/topic/%E6%96%87%E5%AD%97%E3%81%AE%E8%83%8C%E6%99%AF%E3%81%AE%E4%B8%8D%E5%85%B7%E5%90%88/) in the Japanese forum.

Simple site, using Rivington.

**Comment by carolframen** [comment]
Got another one, #5763092-zd Premium using Blink (retired)

**Comment by carolframen** [comment]
5764357-zd Premium using Dyad 2

**Comment by carolframen** [comment]
Another one #5764761 this one is on the personal plan, so no CSS workaround. Gateway theme

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: Could Not Replicate
- Tested on Self-hosted: Could Not Replicate
- Replicable on Core? No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can only replicate on a WordPress.com Simple site, across Classic and FSE themes.

Sample Text:

```
<!-- wp:paragraph -->
<p>Within this sentence, <strong><mark class="has-inline-color has-secondary-color">this section has inline color added</mark></strong>, and then rest does not.</p>
<!-- /wp:paragraph -->
```

*Examples*

Theme: Coutoire
<img width="1403" alt="Screen Shot 2022-12-04 at 1 26 39 PM" src="https://user-images.githubusercontent.com/27249804/205513870-6dbc97c6-b93a-4c52-8c8c-828f4f69601d.png">

Theme: Twenty Twenty Two
<img width="1149" alt="Screen Shot 2022-12-04 at 1 28 25 PM" src="https://user-images.githubusercontent.com/27249804/205513911-357b5853-df17-407e-93c5-37807ba2e403.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 Message to Author
- Escalated here: p1670179266219969-slack-C02FMH4G8

**Comment by jerrysarcastic** [comment]
Also noted in https://wordpress.com/forums/topic/yellow-highlights

Free site so was not able to offer CSS workaround.

**Comment by danielk-am** [comment]
Active theme: Barnsbury
Premium plan. Provided the CSS fix.

```
/* remove background color from highlighted text */
mark {
  background-color: inherit;
}
```

38475228-hc

**Comment by simison** [comment]
Pinged team Calypso in slack (p1670179266219969-slack-dotcom-escalations) as this could be related to CSSTidy removal (p9oQ9f-17X-p2#comment-2146)

**Comment by sguzovskaia** [comment]
Another report: 34149744-hc
Current Theme: Exford and Premium plan. Provided the CSS fix.

/* remove background color from highlighted text */
mark {
  background-color: inherit;
}

**Comment by carolframen** [comment]
Another report on the personal plan, so no workaround. Using the theme Lodestar. #5762501-zd

**Comment by jp-imagines** [comment]
Another report in 5766908-zd-woothemes

**Comment by csonnek** [comment]
Another report: https://wordpress.com/forums/topic/colors-on-headlines/?view=all

**Comment by sguzovskaia** [comment]
Another report: 32019941-hc
Current Theme: Karuna and Premium plan. Provided the CSS fix.

**Comment by csonnek** [comment]
Another report: https://wordpress.com/forums/topic/how-to-opt-out-of-updates-2/?view=all

**Comment by thekingsprojects** [comment]
Another one here: 5765952-zen

Provided the CSS workaround.

**Comment by kuropixel** [comment]
Encountered in 33893830-hc.
Simple site, Theme: Capoverso

Provided CSS workaround previously given in a different bug report.

**Comment by sanjeev00733** [comment]
Another report in 38506003-hc

**Comment by jromales** [comment]
38506629-hc - I provided the CSS workaround.

**Comment by millerf** [comment]
Another report 5767679-zd-woothemes

**Comment by vinnykaur** [comment]
5766043-zen 

Personal plan so I asked the to explicitly change the background color of highlight.

**Comment by vinnykaur** [comment]
5762555-zen

**Comment by rakshitwesley** [comment]
Reported here: 34951859-hc
5769332-zd-woothemes

**Comment by rakshitwesley** [comment]
Reported here: 37674780-hc
5768753-zd-woothemes

**Comment by Sandkorner** [comment]
Another one here: 37729799-hc
5762659-zd

Personal plan, so no CSS workaround used.

**Comment by Joshgrygiel** [comment]
Another: 25302927-hc 

I gave the user the CSS workaround above

**Comment by sguzovskaia** [comment]
Another report in 5496100-ch. Personal plan so no workaround was given.

**Comment by sourourn** [comment]
Another report #38124300-hc, shared CSS workaround

**Comment by deancroyal** [comment]
Another report in 37777153-hc. Personal plan, no workaround.

**Comment by cuemarie** [comment]
📌 Note
-

Thanks for all the reports folks! Just FYI to HE's that a fix is in progress. You can check on developments here: p1670179266219969-slack-C02FMH4G8

**Comment by hacchism** [comment]
Another report in 5767389-zd

Free plan, so no CSS workaround used.

**Comment by daria2303** [comment]
38513026-hc

**Comment by sanjeev00733** [comment]
Another report in 37339669-hc

The issue also appears in the reader. The user has manually set the background color to white so they don't see the issue in the actual post but in the reader. For example this post in reader feed https://wordpress.com/read/feeds/126655055/posts/4397348701

**Comment by the-misha** [comment]
Another report: 37808428-hc / 5772682-zd-woothemes

User is changing link color with highlight, and gets the yellow background. Personal site, so no CSS possible. User would like to be notified when a fix is in place.

**Comment by hngdny** [comment]
Another report in 37173631-hc

Advised to use set highlight background color to match site content background.

**Comment by sajmes** [comment]
38564978-hc

Added CSS.

**Comment by metabreakr** [comment]
Looks like there's a duplicate here: https://github.com/Automattic/wp-calypso/issues/70738

**Comment by thekingsprojects** [comment]
Another case here: 5771810-zen

Personal plan, so not possible to give them the CSS at the moment.

**Comment by vinnykaur** [comment]
8063387-hc 

Shared CSS.

**Comment by aleone89** [comment]
Another report on https://wordpress.com/forums/topic/changing-text-color-in-a-cover-block/?view=all

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/links-appearances-discrepancy/?view=all

**Comment by fullofcaffeine** [comment]
Hi fellows! The fix for simple sites has been shipped in D94491-code. Thanks for the report and your patience! AT fix is incoming, I'll post a message when it's up.

**Comment by fullofcaffeine** [comment]
> Hi fellows! The fix for simple sites has been shipped in D94491-code. Thanks for the report and your patience! AT fix is incoming, I'll post a message when it's up.

By the way, since the issue happened at save-time, in order to fix it you should tell the user to re-save the post.

**Comment by fullofcaffeine** [comment]
AT fix has been shipped, too ✅

**Comment by chrisanez** [comment]
5765952 - free plan, no CSS

**Comment by chrisanez** [comment]
5767775, provided CSS workaround

**Comment by dev-sabbir** [comment]
5775351-zd-woothemes - Personal plan

Fixed after re-saving the post as mentioned here: https://github.com/Automattic/wp-calypso/issues/70675#issuecomment-1342977601

**Comment by danielk-am** [comment]
New one, `5805923-zen`, where the <mark> tag does not have any class and style attributes.

Shared the following CSS.

```
/* Remove the background color from the mark tag */
mark {
  background-color: unset;
}
```

Another workaround is to recreate the block by copying and pasting it without formatting.

**Comment by 1dr0** [comment]
New one, where the <mark> tag does not have any class and style attributes.

Shared the following CSS.

```
/* Remove the background color from the mark tag */
mark {
  background-color: unset;
}
```

Another workaround is to recreate the block by copying and pasting without formatting.

**Comment by cintacks** [comment]
User had custom CSS module removed and the underlying highlight issue wasn't fixed but they reported they were able to fix it:

```I managed to remove this yellow by clicking on "learn more", "highlight", "background" and finally "delete".```

5867299-zd-woothemes
