### ISSUE TITLE
[Bug] - .post-thumbnail failing to scale properly on simple sites, many themes

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#77561]
### Quick summary

Across a number of themes on Simple sites, elements with class `.post-thumbnail` are failing to scale properly.  (Commonly the Blog Posts Block and Single Post's Featured Images).

With some themes (Varia Children), the effects are only seen on mobile, but with others (Morden) the effects are seen on the desktop site.  HEs have been reporting these as theme-specific issues, but in all cases there seems to be a very similar underlying issue - the following CSS:

```
header *, main *, footer * {
    max-width: unset;
}
```

Creating this issue to escalate from a central place.  Theme-specific symptoms can be seen on the following reports:
- https://github.com/Automattic/themes/issues/7095
- https://github.com/Automattic/themes/issues/7099
- https://github.com/Automattic/wp-calypso/issues/76687
- https://github.com/Automattic/wp-calypso/issues/77466
- https://github.com/Automattic/themes/issues/7067

### Steps to reproduce

1. Activate Morden on a Simple site
2. Create a page with the Blog Posts block set to Grid, ensuring it is displaying posts with featured images
3. Publish and view page _(observe size of .post-thumbnails)_
4. View a single post page _(observe size of featured image in a wide screen browser window)_

### What you expected to happen

The featured images to scale to their proper contained size

### What actually happened

![Markup on 2023-05-30 at 10:56:10](https://github.com/Automattic/wp-calypso/assets/27249804/d886cd3d-62b4-47f6-af85-a9ae6f54eb16)

https://user-images.githubusercontent.com/27249804/240387635-b1e664ac-54b2-42db-82ad-0279cceb0e60.mov

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
Future HEs who report this issue - in addition to the interaction link, please note the theme of the site impacted & a brief description of the symptom, just for better tracking of how it's impacting different themes.

**Comment by cuemarie** [comment]
Reported here: 6347742-zd-woothemes
(Internal report: p1685483537034589-slack-C03TY6J1A )

Theme: Morden
Symptom: Site Logo in header not scaling on mobile devices

This CSS corrects the issue:

```
/* Correct header response | xxxx-z */
footer *, header *, main * {
    max-width:100%;
}
```

**Comment by helenaartmann** [comment]
~~Report here: 6346503/zd-woothemes~~
~~Theme: Varese~~
~~Symptom: Featured image on posts not scaling on mobile devices~~

_Update - I looked into this as this is an AT site using an FSE theme, and this instance is just a matter of how they've set up the block in the site editor. See findings here: p1685492257994579/1685490604.258779-slack-C03TY6J1A_ -cuemarie

**Comment by syhussaini** [comment]
It appears on the Exford theme as reported on 6348499-zen
The featured images in single Post view do not scale down on Mobile

**Comment by ghost** [comment]
It appears on the Exford theme as reported on 6349199-zen
Featured Image not scaling on mobile, CSS fix given.

**Comment by dolgelukkig** [comment]
Theme: Exford
Plan: Premium
Fixed with CSS 
6349186-zd

**Comment by rinazrina** [comment]
Reported here: 6348551-zd-woothemes

Theme: Morden
Symptom: Site Logo in header not scaling on mobile devices

The issue only appears when I'm visiting the site while logged out of my WordPress.com account.

Provided the CSS workaround.

**Comment by cuemarie** [comment]
I've escalated this again, this time here: p1685552117465769-slack-C02FMH4G8

Previous investigations (p1685547803270069/1685056613.665109-slack-C029FM1EH) agree this doesn't seem like just a themes issue, but we're still not clear on what's causing this yet. @pbking left some detailed notes in [this comment](https://github.com/Automattic/themes/issues/7095#issuecomment-1570465555) as well.

**Comment by TeniCola** [comment]
Another case in 6351399-zen -- "lately, we are seeing an formatting issue in mobile phones viewing"

Theme: Hever
Plan: Premium

I provided the CSS workaround and the user is good to go, but asked for a follow-up regarding this issue, if possible

**Comment by christianguerrag** [comment]
Another one 6331972-zen provided CSS workaround.
Theme: Maywood
Plan: Premium

**Comment by carolframen** [comment]
6341834-zd 

Theme: Shawburn
Plan: Personal

**Comment by cuemarie** [comment]
A fix has been deployed to address the underlying problem here: p1685552117465769-slack-C02FMH4G8 ( https://github.com/Automattic/minifiers/pull/10 )

📌 ACTIONS
- Closing as fixed

⏭ **NEXT**
- [x] Batch reply for the noted interactions on this and the linked issues above

**Comment by cuemarie** [comment]
Hi everyone 👋 Just a quick note to let you all know I have finished following up with affected users reported in this thread, as well as all users reported in the 5 issues that were merged to this report:

- https://github.com/Automattic/themes/issues/7095
- https://github.com/Automattic/themes/issues/7099
- https://github.com/Automattic/wp-calypso/issues/76687
- https://github.com/Automattic/wp-calypso/issues/77466
- https://github.com/Automattic/themes/issues/7067

Thanks for the reports, please let us know if anyone reports that their site continues to present this issue (following a hard-refresh/cache clear).
