### ISSUE TITLE
Single Posts' CSS overwritten by https://s0.wp.com/_static/??-...

### ISSUE THREAD

**Issue by OmarFPG** [Automattic/wp-calypso#83982]
### Quick summary

I've found three tickets already where users complain about their blog posts having certain elements looking different than before, mainly regarding colors. I've reviewed them, and I found CSS from https://s0.wp.com/_static/??-/wp-content/mu-plugins/comment-likes, or https://s0.wp.com/_static/??-/wp-content/admin-bar, or others that are overwriting the posts' default CSS.

**More details:**
https://a8c.zendesk.com/agent/tickets/7263009
Theme: Argent (Free)
Site Editor active: No
Membership: Personal
Link to a sample post: https://mlizboyle.com/2023/08/11/what-i-learned-from-climbing-a-hard-route-and-what-it-has-to-do-with-the-rest-of-life/
![image](https://github.com/Automattic/wp-calypso/assets/122303439/5a5a162a-5138-4dc4-a705-e60fcf841342)

---

https://a8c.zendesk.com/agent/tickets/7269699
Theme: Balasana (Free)
Site Editor active: No
Membership: Personal
Link to a sample post: https://petsitterchambery.fr/2023/09/28/transport-dun-chien-en-voiture-quel-est-la-reglementation/
![image](https://github.com/Automattic/wp-calypso/assets/122303439/59b5a437-1829-497a-b9a0-dab4f655722a)

---

https://a8c.zendesk.com/agent/tickets/7261995
Theme: Arcane (Premium, Retired)
Site Editor active: No
Membership: Premium
Link to a sample post: https://clarehoran.com/2023/11/07/composition-quotes-11/
![image](https://github.com/Automattic/wp-calypso/assets/122303439/4a6d95c3-1296-49c4-824d-89b1e3cf6655)

An available workaround would be providing CSS to the user if they're on a Premium plan or above, but this is not ideal.

### Steps to reproduce

N/A I haven't found a way to replicate this yet.

### What you expected to happen

The posts' styles should remain consistent with the rest of the site's style and the theme's default options.

### What actually happened

Other styles are being applied, mostly noticeable in coloring for elements such as links, texts or buttons.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

**Comment by rinazrina** [comment]
Another report: 7259280-zd-a8c

**Comment by cuemarie** [comment]
Another possible report here: 7279301-zen
Theme: Hemingway Rewrittin
Simple site, premium plan

Example of what the user is describing:

> On my blog page, everything appears correct:  The sidebar is visible, the body text is black, and the title links are cyan.  On my most recent blog post, the sidebar is missing and the link at the bottom to previous posts is a weird aqua colour, and my Quote block has gone entirely grey

**Comment by cuemarie** [comment]
Possibly the same as https://github.com/Automattic/themes/issues/7460
Escalated here: p1699464090252049-slack-C02FMH4G8

**Comment by autumnfjeld** [comment]
For both https://github.com/Automattic/themes/issues/7460#top and Argent:  I could _not_ reproduce this on a site created one month ago auttest9coct.wordpress.com, but I _could_ reproduce it on a site I created in 2020.  Both are simple sites.   A quick skim through the affected sites shows that they are older sites.   Maybe a clue.

**Comment by sajmes** [comment]
7263009-zd-a8c - just noting this user would like to be notified once resolved. They chatted with us in 7294122-zd-a8c

**Comment by OmarFPG** [comment]
Got another ticket/user affected by this bug: 7272145-zen. The user is very comprehensive but still finds it tedious.

**Comment by OmarFPG** [comment]
Oh wow it seems it's affecting home pages on some sites as well now:

Site: https://fulocultural.com/
Theme: TheFour (Premium, Retired)
Site Editor active: No
Premium membership.
Full ticket link: https://a8c.zendesk.com/agent/tickets/7294246
![image](https://github.com/Automattic/wp-calypso/assets/122303439/2b441f5e-120a-4f32-b0c9-14b5fcf4e31d)

**Comment by alshakero** [comment]
Hi! Can you confirm this is fixed now?

**Comment by OmarFPG** [comment]
Hi @alshakero thank you so much man, I can confirm it's fixed for the single blog posts, I just checked all 4 cases I found, and they're working great. 

Can you check the one from my last comment from yesterday? It affected a homepage, and it isn't fixed yet, so probably it's another bug then.

I'll report back to the single post users for now! 😃

**Comment by alshakero** [comment]
Can you share what's the homepage issue? I'm not sure I get it.

**Comment by OmarFPG** [comment]
This site: https://fulocultural.com/ if you inspect the navigation bar you'll see what I mean 🙂 the nav menu links are white right now because they're picking up CSS from https://s0.wp.com/_static/??-.......

**Comment by taipeicoder** [comment]
Closing via D128515-code. See p1699464090252049-slack-C02FMH4G8 for related conversation.
