### ISSUE TITLE
Using editor commands on sites with the Default view active results to a 404 redirection

### ISSUE THREAD

**Issue by jimjasson** [Automattic/wp-calypso#86000]
### Quick summary

When the Default view is used for pages and someone creates a new page and uses CMD + K to navigate to "Single Posts", they they get redirected to a 404 page.

### Steps to reproduce

1. Set up a new Creator site.
2. Navigate to the Pages tab.
3. Select the Default View.
4. Create a new page.
5. Click CMD + K.
6. Select "Single Posts".
7. See the 404 error.

### What you expected to happen

I expect to be redirected to the template as expected.

### What actually happened

I am redirected to a 404 page.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

I can replicate this issue both on Creator and Woo Express sites. 

Here's a short video: 

https://github.com/Automattic/wp-calypso/assets/25955483/f6a22aca-1c49-4dbf-bbc3-7060a243dc13

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##

VIDEO:
Please see video provided by OP

STEPS TO REPLICATE
- Set up a new Creator site.
- Navigate to the Pages tab.
- Select the Default View.
- Create a new page.
- Select blank template
- Click CMD + K.
- Select "Single Posts".
- Get the "refused to connect" error.
 
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 

## 📌 ACTIONS ##
Triaged

**Comment by lsl** [comment]
The nested iframe isn't able to navigate the top level page, we need the URL to be swapped with a wpcom one similar to what we do for other wp-admin urls:

https://github.com/Automattic/wp-calypso/blob/955b956b70257df047c88f4343065cf3011641d5/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L706-L710

**Comment by inaikem** [comment]
@mmtr 👍

**Comment by obenland** [comment]
@inaikem @mmtr What's the status on this? Why is this a blocker?

**Comment by lsl** [comment]
Not a blocker. High maybe. Was hoping this would have been fixed by iframe removal by now 😬

**Comment by mmtr** [comment]
> What's the status on this?

@xavier-lc was working on a fix and already merged, but don't know if's been shipped. Xavier, can you confirm?

> Why is this a blocker?

@ianstewart flagged it as a blocker on the last Dotcom Triage Group session. Every navigation issue (i.e. you click on something and you don't land on the expected place), including commands from the command palette, should be considered critical issues.

**Comment by mmtr** [comment]
Looks like @xavier-lc forgot to deploy the changes, and @lsl did that today (D164295-code), so we can close this one out.

**Comment by lsl** [comment]
I was still seeing this in production after deploying that change. Maybe a Firefox only issue now or something?

**Comment by xavier-lc** [comment]
Tha nks for the deploy, @lsl. With `I was still seeing this in production after deploying that change` you mean you can still reproduce the error? I've just checked on brave and firefox and it worked.

**Comment by mmtr** [comment]
@lsl note that the wpcom-block-editor scripts [are cached for 24h](https://github.com/Automattic/jetpack/blob/15270796f2107a3168fd7e53f066c9dbc8c4c087/projects/packages/jetpack-mu-wpcom/src/features/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L329), so you might still be loading the old ones.

**Comment by xavier-lc** [comment]
I've found that pressing the `ENTER` key on the commands wasn't working properly, here's the fix: https://github.com/Automattic/wp-calypso/pull/95575

**Comment by lsl** [comment]
>  so you might still be loading the old ones.

I invalidated those, p1729574805314119/1729487009.644859-slack-CRWCHQGUB I think I must have been using the enter key 😄
