### ISSUE TITLE
Migration signup flow: Incorrect INR/MXN/PHP plan price and refund period

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#92210]
### Quick summary

Refer paYKcK-4P7-p2#comment-3558. In the plans step of https://wordpress.com/setup/hosted-site-migration/, the refund period for monthly plans is wrongly shown as 14 days. In INR, MXN, and PHP currencies, the plan price displayed does not include the 20% discount.

### Steps to reproduce

1. On a logged-out incognito window, visit wordpress.com/?currency=INR to set your browser currency. Wait till the plan prices are rendered on the page.
2. Now navigate to https://wordpress.com/setup/hosted-site-migration/ by pasting this in your browser address bar. After you've signed up, enter "matt.com" in the "Let's find your site" step. In the next step to import content, select WordPress, and in the next step select "Migrate site".  
3. In the next step, select "I'll do it myself"
4. You should now be on the plans step. 

### What you expected to happen

1. Plan price for the Creator plan should be INR 640 with a 20% discount. 
2. Refund period for a monthly plan should be 7 days.
3. Selecting Monthly from the dropdown should show the support option crossed-out.

### What actually happened

1. Plan price for the Creator plan is displayed as INR 800.
2. Refund period for the monthly plan is displayed as 14 days.
3. Monthly plan is shown to have "Priority 24/7 support".

<img width="1055" alt="Screenshot 2024-06-28 at 3 36 55 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/d112cc7c-24e9-4196-abe1-7b8ca224deac">

<img width="533" alt="Screenshot 2024-06-28 at 3 39 17 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/d5e05002-cc01-4204-8762-3f47a5ee6b54">

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by niranjan-uma-shankar** [comment]
FYI @Automattic/serenity team and @Automattic/martech-decepticons .

**Comment by daledupreez** [comment]
Thanks for reporting, @niranjan-uma-shankar! I'll take a look at both items -- @Automattic/nexus have also been working on this page.

**Comment by daledupreez** [comment]
Hmmm... The issue with the incorrect price is/was caused by https://github.com/Automattic/wp-calypso/pull/92088, which we merged late yesterday. After that change, we're using the site-specific plans API so we can pick up any introductory offer data. However, we're intentionally using the `getSitePlanRawPrice()` selector because it ignores the discounted price, as we don't want to include discounts stemming from the plan upgrade credit. However, I don't see any way to determine the cause/origin of the discount.

@niranjan-uma-shankar, is that 20% discount an upfront discount or an ongoing/always-on discount?

**Comment by niranjan-uma-shankar** [comment]
> The issue with the incorrect price is/was caused by https://github.com/Automattic/wp-calypso/pull/92088,

Looks like this PR was merged just 17 hours back but I was seeing the issue with the price even much earlier, as reported in paYKcK-4P7-p2#comment-3558.

> is that 20% discount an upfront discount or an ongoing/always-on discount?

The 20% discount is offered to users who are on the free plan (and that includes just signed up users who are seeing the /start/plans page in the signup flow), and is applicable to only the 1Y plan. The discount does not apply to upgrades or renewals, and is shown only to three currencies - INR, MXN, and PHP. Does this help answer your question?

**Comment by niranjan-uma-shankar** [comment]
I see this issue is referenced in https://github.com/Automattic/wp-calypso/pull/92205. @aneeshd16 does your PR help fix the pricing issue reported here?

**Comment by aneeshd16** [comment]
Hi @niranjan-uma-shankar! No, my PR does not fix that issue. I think this issue is being discussed here: https://github.com/Automattic/wp-calypso/pull/92088#discussion_r1658517640

**Comment by daledupreez** [comment]
Thanks for flagging the earlier pricing issue, @niranjan-uma-shankar. I think we actually have an underlying design/UX bug that has influenced all the implementation: we don't have a clear path for showing discounts or introductory offers in the component. A key part of this is that we show free trials in some cases as well.

But the offshoots of that mean that we've _never_ included discount pricing of any kind. So we've always used "the price". The changes that we shipped late last week mean that we can detect site-specific discounts, including the plan upgrade credit, but my work in https://github.com/Automattic/wp-calypso/pull/92094 means we're now mimicking the `/plans/:siteSlug` page in showing a banner for the plan upgrade credit. But as things stand, this specific component doesn't have a good way to show these discounts, so we need to solve for that before we incorrectly communicate renewal pricing to users.

This closely ties in to @aneeshd16's comments in https://github.com/Automattic/wp-calypso/pull/92205 - we have a component that got built to display plan pricing without much familiarity around the possible mechanics involved in pricing and discounts. We've started moving in the right direction as we started working towards some introductory offers, but we still have a gap.

**Comment by daledupreez** [comment]
This issue got lost in the shuffle over the last period, but I've now verified that the following are all working:
 * Plan price for the Creator plan should be INR 640 with a 20% discount.
   - We are showing the 50% discount for the first year discount based on the full price of INR 800/month. This mirrors the way we're showing things in `/pricing` where INR 640 is shown as a discount relative to INR 800/month.
 * Refund period for a monthly plan should be 7 days.
   - This is now correct
* Selecting Monthly from the dropdown should show the support option crossed-out.
   - We're no longer showing support in the features section for the plans, and we're showing monthly, annual, and biannual Business plans side by side.

![Image](https://github.com/user-attachments/assets/93a56d56-868b-4379-ad12-a4e959e76195)
