### ISSUE TITLE
Validate the action bar

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#96202]
Are customers using the logged in action controls on the action bar? I'd like some validation on if this is used or not. 

### Logged in

- What is "Get theme" used for? It's my theme already, right?
- Is "Copy shortlink" relevant? What's it for, why not just copy the URL? It's janky. 
- Collapse this bar seems unhelpful. If the controls are not important to keep, why keep them.

![Image](https://github.com/user-attachments/assets/e15689b4-cf05-4c90-b9c5-2c65779c4a47)

### Logged out

- Do people sign up, or log in from someone here? 
- Do people open it, then choose Manage subscriptions? 

![Image](https://github.com/user-attachments/assets/c46aad9b-35ef-4b4d-a5b1-a8dad2406b71)

### Action bar - whether it should be removed entirely

❓ Does the action bar offer so much value as to be undeletable?
❓  If not, should there be an alternative UX to offer the same functionality/links?

Only the "Edit site" is duplicated in the top admin bar.

The following action items are unique to the floating action bar:

- Subscribe/subscription links
- Copy shortlink 
- Link to site stats
- Direct link to the post in Reader 
- Report post
- Link to current theme

**Comment by davemart-in** [comment]
There are also logged in states while you're on someone else's site:

**At site level:**

![Image](https://github.com/user-attachments/assets/90184d57-ed03-4768-b9c9-3bbc22b63afa)

**At post level:**

![Image](https://github.com/user-attachments/assets/4203ecfb-f65a-4e0b-bd1c-b61c63124841)

**Comment by simison** [comment]
> Does the action bar offer so much value as to be undeletable?
> If not, should there be an alternative UX to offer the same functionality/links?

One of the bigger problems of this bar is that we force it on all sites, regardless if they're blogs or not. It doesn't adapt to the site's theme and there's no way turnign it off.

Regardless of how the website design looks like, on WP.com it'll always have a banner visible:

Posts
<img width="420" src="https://github.com/user-attachments/assets/1d4dbabb-dc28-4d8b-bf76-ab1ed3282e7a"/>

Other pages
<img width="420" src="https://github.com/user-attachments/assets/f8d92c55-90ad-4916-aa05-a35ecd2d850c"/>

Desktop (posts)
<img width="800" src="https://github.com/user-attachments/assets/bdacc878-59b7-4de3-9da1-15d28dd46bac"/>

The bar dissapears when scrolling down, and re-appears when scrolling up, making it a bit harder to actually use it.

I'll pull some stats on clicks and post on the P2: p58i-ioo-p2#comment-65036

As for logged in UI, I understood the "edit site" etc items originated when WP.com masterbar looked different from core's and didn't have "customize", "new" etc links visible, and hence they were put to action bar. But that impression could be wrong; the action bar has been there for a really long time. From times when WP.com was simple sites only and mainly a blogging platform.

Core masterbar:
<img width="600" src="https://github.com/user-attachments/assets/1ed121c1-92c2-4497-93c9-f1193e1e8c28"/>

WP.com masterbar:
<img width="600" src="https://github.com/user-attachments/assets/43f5a81e-07e5-4786-9c94-2874e573762f"/>

Action bar (logged in):
<img width="300" src="https://github.com/user-attachments/assets/248bfa07-417b-4f93-80e6-67b309a9493f"/>


> Is "Copy shortlink" relevant? What's it for, why not just copy the URL? It's janky.

Back in day Twitter had message length limit which was quite short, and shortlinks were helpful. These days it's more common and better to just post the full URL.

![Image](https://github.com/user-attachments/assets/83afde2f-d2a2-4b39-b1b2-2a265321fe49)

**Comment by davemart-in** [comment]
> One of the bigger problems of this bar is that we force it on all sites, regardless if they're blogs or not. It doesn't adapt to the site's theme and there's no way turnign it off.

We should fix these issues.

**Comment by jameskoster** [comment]
For logged in users this widget has a lot of conceptual overlap with the admin bar. There are even duplicative actions "Edit Site", "Edit", etc. We could streamline things by migrating valuable actions to the admin bar, and otherwise removing the action bar.

I acknowledge we also need to consider the logged-out state, but I also question the value there. Anecdotally I really dislike that I'm forced to display this element to visitors on my sites, and always add custom css to ensure it doesn't appear on the frontend. Unless it's a big driver of signups/engagement I'd consider removing it, or at least providing an option for site owners to hide it.

**Comment by davemart-in** [comment]
@jameskoster just noting that there is some deduplication already happening here: https://github.a8c.com/Automattic/wpcom/pull/169373

Repeating what I shared in [another related issue](https://github.com/Automattic/wp-calypso/issues/94079#issuecomment-2572876690):

> I'd ask that we please not remove it completely. It is still valuable, especially for blogger engagement.
> 
> Happy to:
> 
> A) Cull links that no longer make sense.
> B) [Make the action bar optional](https://github.com/Automattic/wp-calypso/issues/53830) - so anyone could turn it off if they want (but still defaulting it to be on)
> C) Redesign the action bar to align more with Gutenberg. Here were a few designs I shared:
> 
> ![Image](https://github.com/user-attachments/assets/6e94d55c-fe6e-4b28-8bc4-ab89083daa61)

I plan to queue up a micro project for one of the Loop squads to add an option (probably under Settings -> General) to toggle the entire action bar off for folks who prefer not to have it on their site.

Also related: @annezazu shared a [helpful recap issue](https://github.com/Automattic/wp-calypso/issues/98042).

**Comment by jameskoster** [comment]
Thanks for the reference Dave :) 

Forgive me as I'm still getting up to speed in wpcom world, but what's the rationale for keeping this as a separate UI widget, rather than moving the actions (post cull) to the admin bar? 

For instance when viewing a post on another users blog while logged in, instead of seeing both the admin bar and the action bar, you'd see something like this:

<img width="1146" alt="Image" src="https://github.com/user-attachments/assets/7dabb6fb-d59a-43c6-8f8e-88eba9ea06a6" />

Then we wouldn't need to worry about having separate options to toggle the admin bar and the action bar.

**Comment by simison** [comment]
Some more convos in P2, internal ref:

- p58i-ioo-p2/#comment-64814
- pfYzsZ-On-p2

**Comment by davemart-in** [comment]
> what's the rationale for keeping this as a separate UI widget, rather than moving the actions (post cull) to the admin bar?

Thanks for mocking that up. I'd say discoverability would be the primary reason.

I suspect moving everything under the admin bar menu would significantly reduce visibility and therefore clicks.

**Comment by jameskoster** [comment]
Without wanting to be flippant, isn't there also a chance it might lead to more clicks? 

On that train of thought could there be a middle-ground where action bar items are added to the admin bar, as a precursor to retiring the action bar down the road?

**Comment by davemart-in** [comment]
> Without wanting to be flippant, isn't there also a chance it might lead to more clicks?

Mind sharing more?

Specifically, I'm trying to figure out why a random person reading a post would click into that dropdown? 

To me, I'd never expect to find engagement links (comment, reblog, subscribe) hidden behind that menu.

**Comment by jameskoster** [comment]
Just a provocation based on familiarity I'd expect registered users to have with the admin bar UX, plus a more prominent position in the viewport (top left vs. bottom right).

If prominence remains a concern, certain actions could be surfaced at the root level instead of the dropdown:

<img width="1146" alt="Image" src="https://github.com/user-attachments/assets/1f22b771-1419-4e13-a906-72ff211e56c4" />

There are many ways to slice it, depending on what actions we want to keep, give more prominence to, etc. I think the admin bar provides a lot of flexibility in that respect.

<img width="1146" alt="Image" src="https://github.com/user-attachments/assets/0720fd38-ecaa-4f5c-aa93-cf4989ec2034" />

**Comment by simison** [comment]
Since the action bar hides on scroll, it's actually hard to spot in casual regular browsing. Site owners don't always even realise it's on their site. Because it's force-enabled on so many millions of sites (i.e. _every_ WP.com site that doesn't hide it with custom CSS), it gets a lot of clicks by its sheer scale.

@jameskoster The top-level masterbar and links within it are "more visible", but unlike the Action bar, the master bar stays hidden when you're not logged in to WP.com. Even if you're logged on to WP.com, sites with custom domains won't "see" that you are. Most folks don't see the masterbar when randomly browsing WP.com sites.

That's why we shipped the floating subscribe button as a more visible replacement:

![Image](https://github.com/user-attachments/assets/2389f257-c654-45c8-adac-0f51f457e8d5)
  
Since it's just the regular Jetpack Subscription button, it blends with the site's styles, is customizable in Gutenberg, doesn't have a WP.com account signup wall, and works with paid newsletters.

If it were enabled by default on every new blog (and just blogs, not on all regular sites), you'd likely get more free and paid subscribers to sites due to more visibility, and less friction. You wouldn't need to re-architect the Action bar to work the same way, and continuing maintaining two things for the same action.

<img width="311" alt="Image" src="https://github.com/user-attachments/assets/ecbc1d2e-2eee-4cc7-9a89-885a9b028877" />

No matter how you change the Action bar's appearance to look like Gutenberg, it will never look like the site and theme, and visitors will have no idea about Gutenberg. It's just another site to them. Because it doesn't blend in at all, you're inclined to keep "hiding" it like the current Action bar, getting much less engagement compared to if it were just much bigger and more visible.

Since Action bar is enabled by default on every site, you'll get folks subscribing to sites who's owners have no intention to gain subscribers or even publish posts. Even worse are sites where publishers use competing products to gain subscribers. It's common to find sites with thousands of subscribers, who then actually used MailerLite, MailChimp or other products instead, so we were just basically stealing subscribers from them and confusing their visitors.

**Comment by jameskoster** [comment]
@simison That reads like an argument for removing the action bar altogether, in favor of blocks (like the Jetpack Subscription button). Is that a fair summary? 

Details users provide during onboarding can dictate whether or not those blocks are included. Hopefully this is trivial to do thanks to block hooks. This approach also provides the flexibility that users need to make these features feel like an actual part of their site, or to pick and choose exactly which ones to include (maybe I want a 'Subscribe' button but not a 'Reblog' one).

**Comment by simison** [comment]
Yeah, the Subscribe blocks are already using block hooks all over (navigation, after posts, etc) and I listed what to enable by default on which WP.com goal here; pfYzsZ-rr-p2

Likes/reblog/sharing/related posts aren't using hooks though, which is a gap since now they won't appear on site editor at all and just appear on the site's frontend. Issue: 

- https://github.com/Automattic/jetpack/issues/36382
