### ISSUE TITLE
Primary site picker when user has only one site

### ISSUE THREAD

**Issue by brunoscopelliti** [Automattic/wp-calypso#9895]
I am opening this as a bug, but you could consider this also a question, because I am not sure what the intended behaviour is.

#### Prerequisite
Having a WordPress account to which only one site is associated.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Open the dropdown that permits to select the Primary site.

#### What I expected
>When the user has only one site it shouldn't show the chevron nor open the dropdown.

It's a quote from @mtias, [here](https://github.com/Automattic/wp-calypso/pull/9754#issuecomment-265433211) .

#### What happened instead
The dropdown works as there were multiple sites.
If I select the only site in the dropdown the next time I open the dropdown it appears empty.

#### Screenshot / Video

* The dropdown works as there were multiple sites.

![toggle](https://cloud.githubusercontent.com/assets/3489757/20998073/655a43c4-bd0b-11e6-8918-2238d9e2bc74.gif)

* If I select the only site in the dropdown the next time I open the dropdown it appears empty.

![difference](https://cloud.githubusercontent.com/assets/3489757/20998155/2b306182-bd0c-11e6-8c69-03c16c3e95de.gif)

#### Context / Source
I stumbled on this while working on the pull request #9754, that is an attempt to uniform the usage of `siteId` over `siteSlug` as preferred method to identify internally a site.
I've written test cases on the basis of the current working of the component in production.
@mtias suggested that probably in this case there was a regression at some point.

Maybe @ebinnion, who introduced sites-dropdown in me/account/main.jsx, when it was still named me/account/index.jsx ([history ref](https://github.com/Automattic/wp-calypso/commit/5138ea7bc18a4435c7a27e6190f016020b8dedeb)), can help us here to remember the original intended behaviour.

**Comment by brunoscopelliti** [comment]
>If I select the only site in the dropdown the next time I open the dropdown it appears empty.

The different behaviour is due to the fact that initially we pass to `site-selector` a siteId as `selected` prop, while it expects a siteSlug.
There's also a warning in console:

```
Warning: Failed prop type: Invalid prop `selected` of type `number` supplied to `SiteSelector`, expected `string`.
```

This cause the `site-selector` filter internal logic to fail sometimes.

This is fixed by #9754.

**Comment by ebinnion** [comment]
> Maybe @ebinnion, who introduced sites-dropdown in me/account/main.jsx, when it was still named me/account/index.jsx (history ref), can help us here to remember the original intended behaviour.

It's been a year, so it's hard to recall the expected behavior. But, I would expect that for one site, we probably don't show the dropdown chevron. Also, we may consider showing something like, "Select a site" as default when the user has not selected a primary site. 

I've had at least a few a12s ping me and ask why a certain site is showing up as their primary site, which is usually because they don't have a primary site selected.

**Comment by brunoscopelliti** [comment]
>I would expect that for one site, we probably don't show the dropdown chevron.

In this case we probably could use the `blocks/site` component. What do you think?

>we may consider showing something like, "Select a site" as default when the user has not selected a primary site.

Is possible that a user has not a primary site?

I would have expected that when I create my first site, it is set as primary site; then the creation of new sites doesn't affect what it's considered the _primary site_.
In fact in my experience it works in this way.

I've also tried to delete the primary site. I had other two sites.
In this case, after a page reload, another of my sites was picked as primary site without the need for me to explicitly select it.

**Comment by alisterscott** [comment]
I tested this again today and it still shows the drop-down for me, although there's only one site listed (plus the same site as the selected site), so it looks like there is two.

Still an issue as if the user has one site the dropdown list just shouldn't exist

<img width="446" alt="screen shot 2017-07-31 at 2 05 38 pm" src="https://user-images.githubusercontent.com/128826/28762391-8a2d11de-75f9-11e7-9774-2c561ffe9294.png">

**Comment by mtias** [comment]
I don't know if this regressed or was never added, but the intention was to not show the chevron and not open the popover if you only have one site.

**Comment by mtias** [comment]
By the way, this also makes me think this could be a fine place to also include an "add new site" hooked up to the WP.com / jetpack flow.

cc @rickybanister @johnHackworth

**Comment by rickybanister** [comment]
That would be great.

We could either have an 'add another site' option in the dropdown that redirects to our interstitial, or we could render the single site (since they can't select another) and add an 'add another site' link below the `site`. I suppose having the 'add' option inside the select would make it more compartmentalized and easier to place in different contexts...

**Comment by rickybanister** [comment]
Here's a quick drawing:

![image](https://user-images.githubusercontent.com/437258/28888894-40801b38-7790-11e7-8d54-f8a9282e1eae.png)

**Comment by mtias** [comment]
We could also add it to the right of the dropdown-box as a regular button to avoid having the arrow on single user sites.
